# Generated by Django 4.1.7 on 2023-03-06 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_category_alter_constructionmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='construction.category', verbose_name='Категория'),
        ),
    ]
