# Generated by Django 4.1.7 on 2023-03-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_constructionmodel_photo_2_constructionmodel_photo_3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionmodel',
            options={'ordering': ['created_at'], 'verbose_name': 'Вид работ', 'verbose_name_plural': 'Виды работ'},
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Url')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото-2')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото-3')),
                ('price', models.CharField(blank=True, max_length=150, verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='construction.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вид работ',
                'verbose_name_plural': 'Виды работ',
            },
        ),
    ]
