# Generated by Django 4.1.7 on 2023-03-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_construction_floors_construction_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('phone_number', models.IntegerField(blank=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
            ],
        ),
    ]
